/*
 * NetFitDataApplet.java
 *
 * Created on 12 February 2008, 11:54
 */

package superdarn.fitDataViewers;

import java.net.URL;

/**
 *
 * @author  nigel
 */
public class DataServerApplet extends javax.swing.JApplet {
    
    /** Initializes the applet NetFitDataApplet */
    @Override
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    String server;
                    URL serverURL = getCodeBase();
                    if ( serverURL != null && serverURL.getProtocol().equals( "http") ) {
                            server = serverURL.getHost();
                    }
                    else {
                            server = "test.ion.le.ac.uk";
                    }
                    netServerBean.setServer( server );
                    netServerBean.setNetFit( netFitBean );
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        netFitBean = new superdarn.fitDataBeans.FitBean();
        netServerBean = new superdarn.fitDataBeans.NetServerBean();

        panel.setLayout(new java.awt.BorderLayout());
        panel.add(netFitBean, java.awt.BorderLayout.CENTER);
        panel.add(netServerBean, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private superdarn.fitDataBeans.FitBean netFitBean;
    private superdarn.fitDataBeans.NetServerBean netServerBean;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
    
}
