/*
 * NetFitViewApplet.java
 *
 * Created on 22 July 2003, 13:46
 */

package superdarn.fitDataViewers;

import java.net.URL;

import javax.swing.JApplet;


/**
 *
 * @author  nigel
 */
public class NetFitViewApplet extends JApplet {
    
    private static final long serialVersionUID = 0x5253505047000030L;
    
    String server;
    
    /** Initializes the applet NetFitViewApplet */
    /** this method will be called by the browser to start the Applet **/
    public void init() {
        
    	// set the server host for the NetServerBean to to be
    	// the host from which the Applet was downloaded.
    	// this is the only host that the Applet is allowed to communicate with.
    	
    	// if the URL of the codebase cannot be found, default to localhost.
    	// This may well throw a security exception.
		URL serverURL = getCodeBase();
		if ( serverURL != null && serverURL.getProtocol().equals( "http") ) {
			server = serverURL.getHost();
		}
		else {
			server = "localhost";
		}
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
    
    private void createAndShowGUI() {
        initComponents();
        validate();
        
        netServer.setServer( server );
        netServer.setNetFit( fitDisplay );
    }
    
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        serverPanel = new javax.swing.JPanel();
        netServer = new fitDataViewers.NetServerBean();
        dataViewPanel = new javax.swing.JPanel();
        fitDisplay = new fitDataViewers.NetFitBean();

        serverPanel.add(netServer);

        getContentPane().add(serverPanel, java.awt.BorderLayout.NORTH);

        dataViewPanel.setBorder(new javax.swing.border.EtchedBorder());
        fitDisplay.setEnabled(false);
        dataViewPanel.add(fitDisplay);

        getContentPane().add(dataViewPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
            
    
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataViewPanel;
    private fitDataViewers.NetFitBean fitDisplay;
    private fitDataViewers.NetServerBean netServer;
    private javax.swing.JPanel serverPanel;
    // End of variables declaration//GEN-END:variables
    
    
    
}
