/*
 * NetFitViewApplet.java
 *
 * Created on 22 July 2003, 13:46
 */

package superdarn.fitDataViewers;

import javax.swing.JFrame;


/**
 *
 * @author  nigel
 */
public class NetFitViewApplication extends JFrame {
    
    private static final long serialVersionUID = 0x5253505047000031L;
    
    
	public static void main(String[] args) {
		
		if ( args.length != 1 ) {
			System.err.print("NetFitViewApplication requires 1 argument,");
			System.err.println(" the server on which the realtime data servlet is running ");
			System.exit(1);
		}
				
		NetFitViewApplication fitView = new NetFitViewApplication();

		fitView.init(args[0]);

		fitView.pack();
		fitView.setVisible(true);

	}

    /** Initializes the applet NetFitViewApplet */
    public void init(String server) {
        
        initComponents();
        netServer.setServer( server );
        netServer.setNetFit( fitDisplay );
    }
    
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        serverPanel = new javax.swing.JPanel();
        netServer = new fitDataViewers.NetServerBean();
        dataViewPanel = new javax.swing.JPanel();
        fitDisplay = new fitDataViewers.NetFitBean();

        serverPanel.add(netServer);

        getContentPane().add(serverPanel, java.awt.BorderLayout.NORTH);

        dataViewPanel.setBorder(new javax.swing.border.EtchedBorder());
        fitDisplay.setEnabled(false);
        dataViewPanel.add(fitDisplay);

        getContentPane().add(dataViewPanel, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
            
    
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataViewPanel;
    private fitDataViewers.NetFitBean fitDisplay;
    private fitDataViewers.NetServerBean netServer;
    private javax.swing.JPanel serverPanel;
    // End of variables declaration//GEN-END:variables
    
    
    
}
