/*
 * FanPanel.java
 *
 * Created on 01 May 2008, 15:21
 */

package uk.ac.le.sppg.superdarn.dataDisplay.fanWindow;

import java.awt.FontMetrics;
import java.text.DateFormat;
import java.util.TimeZone;

/**
 *
 * @author  nigel
 */
public class FanPanel extends javax.swing.JPanel {
    
    /** Creates new form FanPanel */
    public FanPanel() {
        dateFormat.setTimeZone( TimeZone.getTimeZone("GMT") );
        initComponents();
    }
    
    private FontMetrics metrics;
    private DateFormat dateFormat = DateFormat.getDateTimeInstance( DateFormat.LONG, DateFormat.LONG );

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        topLeftPanel = new javax.swing.JPanel();
        CPIDpanel = new javax.swing.JPanel();
        dateField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CPIDField = new javax.swing.JTextField();
        topRightPanel = new javax.swing.JPanel();
        newDataField = new javax.swing.JLabel();
        fanPanel = new javax.swing.JPanel();
        radarChooserPanel = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        bottomPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        beamField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        freqField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        noiseField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        attnField = new javax.swing.JTextField();
        legendPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        topPanel.setLayout(new java.awt.BorderLayout());

        dateField.setEditable(false);
        dateField.setText("01 May 2008 14:11:00 GMT");
        dateField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dateField.setFocusable(false);
        CPIDpanel.add(dateField);

        jLabel1.setText("CPID: ");
        CPIDpanel.add(jLabel1);

        CPIDField.setColumns(4);
        CPIDField.setEditable(false);
        CPIDField.setText("CPID");
        CPIDField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CPIDField.setFocusable(false);
        CPIDField.setRequestFocusEnabled(false);
        CPIDField.setVerifyInputWhenFocusTarget(false);
        CPIDpanel.add(CPIDField);

        topLeftPanel.add(CPIDpanel);

        topPanel.add(topLeftPanel, java.awt.BorderLayout.WEST);
        topPanel.add(topRightPanel, java.awt.BorderLayout.EAST);

        newDataField.setForeground(java.awt.Color.red);
        newDataField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newDataField.setText("No new data received");
        topPanel.add(newDataField, java.awt.BorderLayout.CENTER);

        add(topPanel, java.awt.BorderLayout.NORTH);

        fanPanel.setLayout(new java.awt.BorderLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        radarChooserPanel.add(jComboBox1);

        jButton1.setText("jButton1");
        radarChooserPanel.add(jButton1);

        fanPanel.add(radarChooserPanel, java.awt.BorderLayout.NORTH);

        add(fanPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Beam: ");
        bottomPanel.add(jLabel2);

        beamField.setColumns(3);
        beamField.setEditable(false);
        beamField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        beamField.setFocusable(false);
        bottomPanel.add(beamField);

        jLabel3.setText("Freq:");
        bottomPanel.add(jLabel3);

        freqField.setColumns(6);
        freqField.setEditable(false);
        freqField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        freqField.setFocusable(false);
        bottomPanel.add(freqField);

        jLabel4.setText("Noise: ");
        bottomPanel.add(jLabel4);

        noiseField.setColumns(4);
        noiseField.setEditable(false);
        noiseField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        noiseField.setFocusable(false);
        bottomPanel.add(noiseField);

        jLabel5.setText("Attn: ");
        bottomPanel.add(jLabel5);

        attnField.setColumns(4);
        attnField.setEditable(false);
        attnField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        attnField.setFocusable(false);
        bottomPanel.add(attnField);

        add(bottomPanel, java.awt.BorderLayout.SOUTH);

        legendPanel.setLayout(new javax.swing.BoxLayout(legendPanel, javax.swing.BoxLayout.X_AXIS));
        add(legendPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPIDField;
    private javax.swing.JPanel CPIDpanel;
    private javax.swing.JTextField attnField;
    private javax.swing.JTextField beamField;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JTextField dateField;
    private javax.swing.JPanel fanPanel;
    private javax.swing.JTextField freqField;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel legendPanel;
    private javax.swing.JLabel newDataField;
    private javax.swing.JTextField noiseField;
    private javax.swing.JPanel radarChooserPanel;
    private javax.swing.JPanel topLeftPanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel topRightPanel;
    // End of variables declaration//GEN-END:variables
    
}
